FROM node:20
EXPOSE 8080
ENV DB_HOST=mysql
RUN useradd expense
RUN mkdir /opt/server/index.js
RUN chown expense:expense -R /opt/server
WORKDIR /opt/server/index.js
COPY package.json .
COPY *.js .
RUN npm install
CMD ["node","index.js"]